// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SampleOnlineMall.Core;

#nullable disable

namespace SampleOnlineMall.WebLogger.Migrations
{
    [DbContext(typeof(EfPostgresWebLoggerDbContext))]
    partial class EfPostgresWebLoggerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SampleOnlineMall.Core.WebLoggerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModifiedDatTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LogLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("SysMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WebLoggerMessage");
                });

            modelBuilder.Entity("SampleOnlineMall.Core.WebLoggerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ItemsPerPage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDatTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("LogsKeepingPeriod")
                        .HasColumnType("interval");

                    b.Property<int>("RefreshPeriodMs")
                        .HasColumnType("integer");

                    b.Property<string>("SysMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WebLoggerSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
